### ISSUE TITLE
ViroVideo is not working

### ISSUE THREAD

**Issue by robertjcolley** [ViroCommunity/viro#75] opened 2021-12-23 22:45 UTC
# Requirements: 
Please go through this checklist before opening a new issue
  - [x] Review the [documentation](https://docs.viromedia.com/)
  - [x] Search for existing issues in: [viromedia/viro](https://github.com/viromedia/viro/issues) & [ViroCommunity/viro](https://github.com/ViroCommunity/viro/issues)
  - [x] Use the latest [ViroReact release](https://docs.viromedia.com/docs/releases)

## Environment
Please provide the following information about your environment:
1. Macbook Pro
2. Device OS & Version: iPhone11 iOS 15.3
3. ViroReact: 2.22.0
4. React Native: 0.65.1

## Description
- [ ] ViroVideo crashes with invariant violation: Unrecognized selector sent to instance

Interestingly, Viro360Video works.

## Reproducible Demo

> ⚠️ NOTE: I've installed viro react from a local download of the viro react to make changes to the viro react source code. All of these issues have been replicated with viro@2.22.0.

#### ViroVideo
https://github.com/NS-BOBBY-C/starter-kit/blob/4d93e7dd3ae05d089573f07f20964e2258a1933d/screens/viro_tests/ViroVideo.tsx#L1-L45

**Comment by NS-BOBBY-C** [comment] 2022-01-11 00:22
Update: @doranteseduardo was not able to reproduce. I'll be double-checking that this is an issue within the next day or so!

**Comment by NS-BOBBY-C** [comment] 2022-01-21 12:47
Closing since I was not able to reproduce in my starter kit on ios or android. https://github.com/NS-BOBBY-C/starter-kit/blob/e79051a6c9d4f0182e20bda872c15430ee0393b8/screens/github_issues/Issue75.tsx

**Comment by andre-sonect** [comment] 2022-02-17 13:14
Still able to reproduce on latest version.

` <ViroARScene onTrackingUpdated={onInitialized}>
          <ViroAmbientLight color="#ffffff" intensity={2500} />
          <ViroNode
            position={[0, 0, 0]}
            rotation={[0, 0, 0]}
            scale={[2.0, 2.0, 2.0]}>
            <ViroVideo
              source={require('../../../assets/animation/wizard.mp4')}
              loop={true}
              position={[0, 2, -5]}
              scale={[2, 2, 0]}
            />
          </ViroNode>
        </ViroARScene>`

**Comment by andre-sonect** [comment] 2022-02-17 17:39
You can close it since my previous comment is now invalid. Devs were using not latest but previous version.

**Closed** 2022-02-17 18:15 UTC
Labels: bug
