### ISSUE TITLE
VR in iOS just display a blank screen.

### ISSUE THREAD

**Issue by sekhuat** [ViroCommunity/viro#5] opened 2021-03-17 12:49 UTC
## Environment
Please provide the following information about your environment:
1. Development OS: Mac
2. Device OS & Version: iOS 14.4 iPhone SE
3. Version: test on both 2.19.0 and 2.20.0
4. Device(s): iPhone SE

## Description
When using the ViroVRSceneNavigator and ViroScene in iOS to display the VR, the device just display a blank screen without any error or exception.

## Reproducible Demo
I had follow the instruction on the Starter Kit page: 
[https://github.com/ViroCommunity/starter-kit](https://github.com/ViroCommunity/starter-kit)

1. git clone https://github.com/ViroCommunity/starter-kit.git
2. cd starter-kit
3. npm install
4. npx pod-install (iOS)
5. (My step) Edit the App.js in the root folder by changing the ViroARSceneNavigator to ViroVRSceneNavigator and the ViroARScene to ViroScene. I also import the ViroVRSceneNavigator and ViroScene at the top of App.js
6. npx react-native run-android or npx react-native run-ios

It work fine in Android but not in iOS. Please help.

**Comment by bilewinters** [comment] 2021-03-17 14:12
Hi @sekhuat thanks for bringing this to our attention.

I'm also able to reproduce this issue on an iPhone 8 running iOS 14.4.

Primarily the current maintainers have focussed on AR rather than VR, so we do not have much experience in this area, but we are keen to understand and fix the issue (and welcome help from anyone else).

**Comment by sekhuat** [comment] 2021-03-29 08:58
Any update on the timeline where the above issue can be fix?

**Comment by doranteseduardo** [comment] 2021-04-15 22:31
The issue is being tackled and will be available in the next major release.

**Comment by RSginer** [comment] 2021-05-25 15:47
same problem here, any updates?

**Comment by NS-BOBBY-C** [comment] 2021-12-18 18:00
Issue is being worked on still.

**Comment by Fernando-7** [comment] 2022-01-17 21:10
> Issue is being worked on still.

Hello NS-BOBBY-C. Do you have any news about the bug fix?

**Comment by NS-BOBBY-C** [comment] 2022-01-17 21:12
@Fernando-7 no update. @doranteseduardo is working on this still.

**Comment by RicardoSMatos** [comment] 2022-01-20 00:35
@NS-BOBBY-C  I have the same problem. Is there an estimated release date for a version with this fix. Thank you.

**Comment by doranteseduardo** [comment] 2022-02-03 05:01
I'll close this issue in favor of #73

**Closed by doranteseduardo** 2022-02-03 05:01 UTC
Labels: to be released
